# Generated by Django 3.0.dev20190802183221 on 2019-08-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('mid_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(verbose_name='date published')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_title', models.CharField(max_length=200)),
                ('loan_amount', models.IntegerField(default=0)),
                ('mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Members')),
            ],
        ),
    ]
